SELECT 'UPDATE NFE_PRC SET ARQUIVO_XML='''||ARQUIVO_XML||''' WHERE ID_NF='||ID_NF||' AND ID_FILIAL=1;' 
FROM NFE_PRC
WHERE ID_FILIAL=1 
AND 
EMISSAO_DATA BETWEEN '2017-01-01' AND '2017-12-31' 
ORDER BY ID_NF
