select 
p.CODPRODUTO AS ID_PRODUTO, 
p.DESCRICAO AS DESCRICAO, 
p.UNIDADE, 
p.REF_FABRICA AS REFERENCIA, 
p.COD_BARRAS AS GTIN,
p.CODIGO_NCM AS NCM, 
p.CODGRUPO, 
g.NOMEGRUPO, 
p.CODFORNECE, 
f.NOME_RAZAO, 
p.PCOMPRA AS VLR_COMPRA, 
p.PVENDA AS VLR_VENDA,
e.SALDO,
p.CADASTRO AS DATA_CADASTRO
from 
TB_PRODUTOS p
JOIN TB_GRUPOS g on p.CODGRUPO=g.CODGRUPO
JOIN TB_FORNECEDORES f on p.CODFORNECE=f.CODFORNECE
JOIN TB_ESTOQUE_SALDO e on p.CODPRODUTO = e.CODPRODUTO
where p.COD_FILIAL=
