select 
t.id AS ID_TRANSFERENCIA,
T.DATA AS DATA_TRANSFERENCIA,
t.id_empresa_sai AS EMPRESA_SAIDA,
T.id_empresa_ent AS EMPRESA_ENTRADA,
T.status,
CASE 
	WHEN T.status=0 THEN
		'PENDENTE'
	WHEN T.status=1 THEN
		'ENVIADO'
		ELSE
		'RECEBIDO'
END,
TI.item AS ITEM,
TI.ID_PRODUTO,
P.DESCRICAO,
TI.VLR_VENDIDO AS VALOR_UNITARIO,
TI.QTDE AS QUANTIDADE,
TI.VLR_BRUTO AS VALOR_BRUTO,
TI.VLR_LIQUIDO AS VALOR_LIQUIDO
FROM TRANSFERENCIAS AS T
JOIN TRANSFERENCIAS_ITENS AS TI ON TI.ID_TRANSFERENCIA = T.ID
JOIN PRODUTO AS P ON P.ID=TI.ID_PRODUTO
WHERE T.STATUS=1 AND T.DATA BETWEEN '2019-01-01' AND '2019-12-31'
